import localFont from "next/font/local";
import Header from "@/components/common/header";
import "./index.scss";
import Footer from "@/components/common/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-100">
      <body
        className={`${geistSans.variable} ${geistMono.variable} d-flex flex-column justify-content-between h-100`}
      >
        {children}
      </body>
    </html>
  );
}
